# ~/.config/hypr/hyprlock.conf

background {
    color = rgba(0, 0, 0, 0.9)
}

input-field {
    size = 300, 40
    outline_thickness = 1
    rounding = 4
    placeholder_text =
    hide_input = true
    font_family = Iosevka Vixelated
}
