background {
    monitor =
    brightness = 1
    color = rgb(000000)
}

input-field {
    monitor =
    size = 450, 48
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.5
    dots_center = true
    dots_rounding = 0
    outer_color = rgb(000000)
    inner_color = rgb(000000)
    font_color = rgb(ffffff)
    font_family = Iosevka Vixelated
    font_size = 32
    check_color = rgba(323232ff)
    fail_color = rgba(32323299)
    fail_text = <b>INCORRECT PASSWORD</b>
    capslock_color = rgba(32323299)
    fade_on_empty = false
    placeholder_text = <b>ENTER PASSWORD</b>
    hide_input = false
    rounding = 0
    position = 0, 0
    halign = center
    valign = center
}
